// apps/cosmix-web/src/components/ui/toast.tsx
"use client";

import { useEffect, useState } from "react";
import { cn } from "@/lib/utils";
import { CheckCircle, XCircle, Info, X } from "lucide-react";

export interface ToastProps {
  id: string;
  message: string;
  type?: "success" | "error" | "info";
  duration?: number;
  onClose: (id: string) => void;
}

export function Toast({ id, message, type = "info", duration = 3000, onClose }: ToastProps) {
  const [isVisible, setIsVisible] = useState(true);

  useEffect(() => {
    const timer = setTimeout(() => {
      setIsVisible(false);
      setTimeout(() => onClose(id), 300);
    }, duration);

    return () => clearTimeout(timer);
  }, [id, duration, onClose]);

  const icons = {
    success: <CheckCircle className="w-5 h-5 text-green-500" />,
    error: <XCircle className="w-5 h-5 text-red-500" />,
    info: <Info className="w-5 h-5 text-blue-500" />,
  };

  return (
    <div
      className={cn(
        "flex items-center gap-3 px-4 py-3 rounded-lg shadow-lg bg-[var(--surface)] border border-[var(--border)] transition-all duration-300",
        isVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-2"
      )}
    >
      {icons[type]}
      <span className="text-sm">{message}</span>
      <button onClick={() => onClose(id)} className="ml-2 p-1 hover:bg-[var(--border)] rounded">
        <X className="w-4 h-4" />
      </button>
    </div>
  );
}

interface ToastContainerProps {
  toasts: Array<{
    id: string;
    message: string;
    type?: "success" | "error" | "info";
  }>;
  onClose: (id: string) => void;
}

export function ToastContainer({ toasts, onClose }: ToastContainerProps) {
  return (
    <div className="fixed bottom-4 right-4 z-50 flex flex-col gap-2">
      {toasts.map((toast) => (
        <Toast key={toast.id} {...toast} onClose={onClose} />
      ))}
    </div>
  );
}

// apps/learn/src/lib/components/ui/Toast.svelte
<script lang="ts">
  import { cn } from "$lib/utils/cn";
  import { X } from "lucide-svelte";

  interface Props {
    message: string;
    type?: "success" | "info" | "warning" | "error";
    show: boolean;
    onclose?: () => void;
  }

  let { message, type = "info", show = $bindable(false), onclose }: Props = $props();

  const typeStyles = {
    success: "bg-green-500/20 border-green-500/30 text-green-400",
    info: "bg-blue-500/20 border-blue-500/30 text-blue-400",
    warning: "bg-yellow-500/20 border-yellow-500/30 text-yellow-400",
    error: "bg-red-500/20 border-red-500/30 text-red-400",
  };

  function handleClose() {
    show = false;
    onclose?.();
  }

  // Auto-hide after 3 seconds
  $effect(() => {
    if (show) {
      const timer = setTimeout(() => {
        show = false;
        onclose?.();
      }, 3000);
      return () => clearTimeout(timer);
    }
  });
</script>

{#if show}
  <div
    class={cn(
      "fixed bottom-8 left-1/2 -translate-x-1/2 z-[100]",
      "flex items-center gap-3 px-5 py-3 rounded-2xl",
      "border backdrop-blur-xl shadow-2xl",
      "animate-slide-up",
      typeStyles[type]
    )}
  >
    <span class="text-sm font-medium">{message}</span>
    <button
      class="p-1 rounded-lg hover:bg-white/10 transition-colors"
      onclick={handleClose}
    >
      <X class="w-4 h-4" />
    </button>
  </div>
{/if}

<style>
  @keyframes slide-up {
    from {
      opacity: 0;
      transform: translate(-50%, 20px);
    }
    to {
      opacity: 1;
      transform: translate(-50%, 0);
    }
  }

  .animate-slide-up {
    animation: slide-up 0.3s ease-out;
  }
</style>
