// apps/tools/src/lib/components/ui/Toast.svelte
<script lang="ts">
import { Check, X, AlertCircle } from "lucide-svelte";

interface Props {
	message: string;
	type?: "success" | "error" | "info";
	visible?: boolean;
	ondismiss?: () => void;
}

let { message, type = "success", visible = false, ondismiss }: Props = $props();

const icons = {
	success: Check,
	error: X,
	info: AlertCircle,
} as const;

const colors = {
	success: "bg-[var(--color-success)]",
	error: "bg-[var(--color-danger)]",
	info: "bg-[var(--color-accent)]",
} as const;

$effect(() => {
	if (visible) {
		const timer = setTimeout(() => {
			ondismiss?.();
		}, 3000);
		return () => clearTimeout(timer);
	}
});

let Icon = $derived(icons[type]);
</script>

{#if visible}
  <div
    class="
      fixed bottom-6 right-6 z-50
      flex items-center gap-3
      px-4 py-3
      bg-[var(--color-surface)]
      border border-[var(--color-border)]
      rounded-[var(--radius-md)]
      shadow-[var(--shadow-card)]
      animate-slide-in-left
    "
  >
    <div
      class="
        w-6 h-6
        flex items-center justify-center
        rounded-full
        {colors[type]}
        text-[var(--color-background)]
      "
    >
      <Icon size={14} strokeWidth={3} />
    </div>
    <span class="font-mono text-sm text-[var(--color-text)]">{message}</span>
  </div>
{/if}

// apps/cosmix-web/src/components/ui/toast.tsx
"use client";

import { useEffect, useState } from "react";
import { cn } from "@/lib/utils";
import { CheckCircle, XCircle, Info, X } from "lucide-react";

export interface ToastProps {
  id: string;
  message: string;
  type?: "success" | "error" | "info";
  duration?: number;
  onClose: (id: string) => void;
}

export function Toast({ id, message, type = "info", duration = 3000, onClose }: ToastProps) {
  const [isVisible, setIsVisible] = useState(true);

  useEffect(() => {
    const timer = setTimeout(() => {
      setIsVisible(false);
      setTimeout(() => onClose(id), 300);
    }, duration);

    return () => clearTimeout(timer);
  }, [id, duration, onClose]);

  const icons = {
    success: <CheckCircle className="w-5 h-5 text-green-500" />,
    error: <XCircle className="w-5 h-5 text-red-500" />,
    info: <Info className="w-5 h-5 text-blue-500" />,
  };

  return (
    <div
      className={cn(
        "flex items-center gap-3 px-4 py-3 rounded-lg shadow-lg bg-[var(--surface)] border border-[var(--border)] transition-all duration-300",
        isVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-2"
      )}
    >
      {icons[type]}
      <span className="text-sm">{message}</span>
      <button onClick={() => onClose(id)} className="ml-2 p-1 hover:bg-[var(--border)] rounded">
        <X className="w-4 h-4" />
      </button>
    </div>
  );
}

interface ToastContainerProps {
  toasts: Array<{
    id: string;
    message: string;
    type?: "success" | "error" | "info";
  }>;
  onClose: (id: string) => void;
}

export function ToastContainer({ toasts, onClose }: ToastContainerProps) {
  return (
    <div className="fixed bottom-4 right-4 z-50 flex flex-col gap-2">
      {toasts.map((toast) => (
        <Toast key={toast.id} {...toast} onClose={onClose} />
      ))}
    </div>
  );
}
